# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DE10Class": "00_Devices.ipynb",
         "DE10": "00_Devices.ipynb",
         "qshell": "01_Scripting.ipynb",
         "get_fpgas": "01_Scripting.ipynb",
         "get_insts": "01_Scripting.ipynb",
         "begin_mem": "01_Scripting.ipynb",
         "end_mem": "01_Scripting.ipynb",
         "read": "01_Scripting.ipynb",
         "format_mem": "01_Scripting.ipynb",
         "write": "01_Scripting.ipynb",
         "read_write": "01_Scripting.ipynb",
         "read_write_all": "01_Scripting.ipynb",
         "program_proj": "01_Scripting.ipynb",
         "compile_proj": "01_Scripting.ipynb",
         "archive_proj": "01_Scripting.ipynb",
         "back_annotate": "01_Scripting.ipynb",
         "write_qsf": "01_Scripting.ipynb",
         "lut_mask": "01_Scripting.ipynb",
         "analyze_timing": "01_Scripting.ipynb",
         "Project": "02_Projects.ipynb"}

modules = ["devices.py",
           "scripting.py",
           "projects.py"]

doc_url = "https://Noeloikeau.github.io/fpyga/"

git_url = "https://github.com/Noeloikeau/fpyga/tree/master/"

def custom_doc_links(name): return None
